Arg, removeHandler on service-wide self.log instead private log in svc.action().
This was causing this message in daily cron job :

  File "/usr/lib64/python2.6/logging/__init__.py", line 1021, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib64/python2.6/logging/__init__.py", line 1129, in _log
    self.handle(record)
  File "/usr/lib64/python2.6/logging/__init__.py", line 1139, in handle
    self.callHandlers(record)
  File "/usr/lib64/python2.6/logging/__init__.py", line 1176, in callHandlers
    hdlr.handle(record)
  File "/usr/lib64/python2.6/logging/__init__.py", line 664, in handle
    self.release()
  File "/usr/lib64/python2.6/logging/__init__.py", line 618, in release
    self.lock.release()
  File "/usr/lib64/python2.6/threading.py", line 136, in release
    raise RuntimeError("cannot release un-aquired lock")
RuntimeError: cannot release un-aquired lock