Docker 1.10.3 doesn't like ":" in cgroup paths anymore
Too bad, we use that when setting docker containers in subsets.
This patch substitutes ':' with dots.

Symptom:

ERROR   spdsvc01.container:c0#29db stderr:
Error response from daemon: Container command not found or does not exist.
Error: failed to start containers: f06d43a02126

and:

$ sudo spdsvc01 docker logs c84611990910
Timestamp: 2016-03-29 19:54:14.961534915 +0000 UTC
Code: System error

Message: stat /sys/fs/cgroup/systemd/spdsvc01/container: no such file or directory

while our cgroup tree is like:

$ ll /sys/fs/cgroup/systemd/spdsvc01/
total 0
drwxr-xr-x  3 root root 0 Mar 29 20:00 ./
dr-xr-xr-x  7 root root 0 Mar 29 19:08 ../
-rw-r--r--  1 root root 0 Mar 29 20:00 cgroup.clone_children
-rw-r--r--  1 root root 0 Mar 29 20:00 cgroup.procs
drwxr-xr-x 10 root root 0 Mar 29 19:09 container:c0/
-rw-r--r--  1 root root 0 Mar 29 20:00 notify_on_release
-rw-r--r--  1 root root 0 Mar 29 20:00 tasks

$ ll /sys/fs/cgroup/systemd/spdsvc01/container\:c0/
total 0
drwxr-xr-x 10 root root 0 Mar 29 20:00 ./
drwxr-xr-x  3 root root 0 Mar 29 20:00 ../
-rw-r--r--  1 root root 0 Mar 29 20:00 cgroup.clone_children
-rw-r--r--  1 root root 0 Mar 29 20:00 cgroup.procs
drwxr-xr-x  2 root root 0 Mar 29 19:09 container.25db/
drwxr-xr-x  2 root root 0 Mar 29 19:09 container.26db/
drwxr-xr-x  2 root root 0 Mar 29 19:09 container.27db/
drwxr-xr-x  2 root root 0 Mar 29 19:09 container.28db/
drwxr-xr-x  2 root root 0 Mar 29 19:09 container.29db/
drwxr-xr-x  2 root root 0 Mar 29 19:09 container.30db/
drwxr-xr-x  2 root root 0 Mar 29 19:09 container.31db/
drwxr-xr-x  2 root root 0 Mar 29 19:09 container.32db/
-rw-r--r--  1 root root 0 Mar 29 20:00 notify_on_release
-rw-r--r--  1 root root 0 Mar 29 20:00 tasks

After this patch, our cgroup tree structure is like this,
which makes docker happy again:

cvaroqui@spd04:~$ ll /sys/fs/cgroup/systemd/spdsvc01/
total 0
drwxr-xr-x  5 root root 0 Mar 29 20:08 ./
dr-xr-xr-x  7 root root 0 Mar 29 20:00 ../
-rw-r--r--  1 root root 0 Mar 29 20:00 cgroup.clone_children
-rw-r--r--  1 root root 0 Mar 29 20:00 cgroup.procs
drwxr-xr-x 10 root root 0 Mar 29 20:07 container.c0/
-rw-r--r--  1 root root 0 Mar 29 20:00 notify_on_release
-rw-r--r--  1 root root 0 Mar 29 20:00 tasks