Fix raw_daemon_request stack when timeout param is None
Add tests
    o TestRawDaemonRequestWithNoTimeout
        o test_returns_received_message
        o test_no_extra_sleep
        o test_cleanup_connexion
        o test_returns_success_without_tries_to_recv_results_when_with_result_param_is_false
        o test_it_sends_correct_message[GET]
        o test_it_sends_correct_message[POST]
        o test_retries_connect_until_succeed
        o test_retries_recv_until_succeed
        o test_returns_status_1_when_connect_error
        o test_returns_status_1_when_recv_error
        o test_always_retry_when_connect_or_recv_error
        o test_result_is_status_1_with_when_send_message_fails
    o TestRawDaemonRequestWithTimeoutIsPositive
        o test_returns_received_message
        o test_fails_when_duration_exceed_timeout_because_of_connect_timeouts
        o test_fails_when_duration_exceed_timeout
    o TestRawDaemonRequestWithTimeoutParamZero
        o test_failfast_when_connect_error
        o test_failfast_when_recv_message_fails

This fix following stack:
    Traceback (most recent call last):
      File "/usr/share/opensvc/opensvc/core/comm.py", line 867, in raw_daemon_request
        encrypted=sp.encrypted
      File "/usr/share/opensvc/opensvc/core/comm.py", line 507, in recv_message
        data = self.recv_messages(*args, **kwargs)
      File "/usr/share/opensvc/opensvc/core/comm.py", line 540, in recv_messages
        raise socket.timeout
    socket.timeout

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/share/opensvc/opensvc/daemon/monitor.py", line 147, in run
        self.do()
      File "/usr/share/opensvc/opensvc/daemon/monitor.py", line 219, in do
        self.orchestrator()
      File "/usr/share/opensvc/opensvc/daemon/monitor.py", line 781, in orchestrator
        self.sync_services_conf()
      File "/usr/share/opensvc/opensvc/daemon/monitor.py", line 288, in sync_services_conf
        self.fetch_service_config(path, ref_nodename)
      File "/usr/share/opensvc/opensvc/daemon/monitor.py", line 328, in fetch_service_config
        resp = self.daemon_get(req, server=nodename)
      File "/usr/share/opensvc/opensvc/core/comm.py", line 721, in daemon_get
        return self.daemon_request(*args, **kwargs)
      File "/usr/share/opensvc/opensvc/core/comm.py", line 733, in daemon_request
        return self.raw_daemon_request(*args, sp=sp, **kwargs)
      File "/usr/share/opensvc/opensvc/core/comm.py", line 870, in raw_daemon_request
        if timeout > 0 and elapsed > timeout:
    TypeError: unorderable types: NoneType() > int()