Detect docker pidfile deleted between exists test and open
Causing this stack:

Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/opensvc/lib/svc.py", line 2075, in wrapper
    if fn():
  File "/opt/opensvc/lib/resContainer.py", line 164, in abort_start
    if self.is_up():
  File "/opt/opensvc/lib/resContainerDocker.py", line 167, in is_up
    if not self.docker_running():
  File "/opt/opensvc/lib/rcDocker.py", line 343, in docker_running
    return self.docker_running_private()
  File "/opt/opensvc/lib/rcDocker.py", line 357, in docker_running_private
    with open(self.docker_pid_file, "r") as f:
IOError: [Errno 2] No such file or directory: '/opt/opensvc/var/registry/docker.pid'