Fix a bad syntax in a error log
Caused:

...
    self.log("service %s postinstall failed: %s", svcpath, exc)
TypeError: 'Logger' object is not callable