Fix a stack on "om node logs" when a peer goes down
Example stack:

  File "/opt/opensvc/opensvc/core/node/node.py", line 4792, in <lambda>
    return sorted(lines, key=lambda x: x.get("t", 0))
AttributeError: 'unicode' object has no attribute 'get'

Caused by the lack of validation of the node dataset during concatenation.
When the peer goes down a list({"error": "...", "status": 1}) dict is
unduly concatenated to the log lines.