Fix 'drpnode' env file parameter parsing
Regression introduced while scoping nodes, drpnodes and nodes
parameters. Only 'drpnode' is affected.

Produced the followinig stack:

Traceback (most recent call last):
  File "/opt/opensvc/lib/svcBuilder.py", line 1607, in build_services
    svc = build(name)
  File "/opt/opensvc/lib/svcBuilder.py", line 1303, in build
    drpnodes |= set([drpnode])
TypeError: unhashable type: 'set'