Fix variable names in openha hb error code path on switch action
Was causing this stack :

Traceback (most recent call last):
  File "/opt/opensvc/lib/svc.py", line 2345, in do_action
    err = getattr(self, action)()
  File "/opt/opensvc/lib/svc.py", line 2478, in switch
    self.sub_set_action("hb", "switch")
  File "/opt/opensvc/lib/svc.py", line 424, in sub_set_action
    self.set_action(self.get_res_sets(type, strict=strict), action=action, tags=tags, xtags=xtags)
  File "/opt/opensvc/lib/svc.py", line 519, in set_action
    r.action(action, tags=tags, xtags=xtags)
  File "/opt/opensvc/lib/resources.py", line 660, in action
    r.action(action)
  File "/opt/opensvc/lib/resources.py", line 221, in action
    self.do_action(action)
  File "/opt/opensvc/lib/resources.py", line 174, in do_action
    self.action_main(action)
  File "/opt/opensvc/lib/resources.py", line 159, in action_main
    getattr(self, action)()
  File "/opt/opensvc/lib/resHbOpenHA.py", line 375, in switch
    raise ex.excError("cannot switch in current state: %s/%s"%(local_state,remote_state))
NameError: global name 'local_state' is not defined