Ip docker bugfixes and enhancements
- support and honor "type = docker" in the resource def
- don't need to specify the "docker" tag anymore
- add container_rid to the keyword dictionnary (fix provisioning
error: Remove unknown keyword 'container_rid' from section 'ip')
- add "docker" as a supported value for ip resource type in the
keyyword dictionnary (fix absent template.ip.docker.env)