Fix ThreadPoolExecutor missing 1 required positional argument: 'max_workers'
max_workers was required before https://github.com/python/cpython/commit/cfd4661e78bd2256caaf80cf29588e5119e787b0

stack example:
    Traceback (most recent call last):
      File "/usr/share/opensvc/opensvc/core/objects/svc.py", line 1121, in do_action
        err = call_action(action)
      File "/usr/share/opensvc/opensvc/core/objects/svc.py", line 1110, in call_action
        err = getattr(self, action)()
      File "/usr/share/opensvc/opensvc/core/objects/svc.py", line 4435, in start
        self.abort_start()
      File "/usr/share/opensvc/opensvc/core/objects/svc.py", line 4568, in abort_start
        with concurrent.futures.ThreadPoolExecutor() as executor:
    TypeError: __init__() missing 1 required positional argument: 'max_workers'