Fix this error:
[root@s64lmwbicqe ~]# /service/etc/erpprdtransco scsireserv
Traceback (most recent call last):
  File "/usr/local/opensvc/bin/../lib/svc.py", line 195, in action
    getattr(self, action)()
  File "/usr/local/opensvc/bin/../lib/svc.py", line 160, in scsireserv
    self.sub_set_action("disk.vg", "scsireserv")
  File "/usr/local/opensvc/bin/../lib/svc.py", line 87, in sub_set_action
    r.action(action)
  File "/service/etc/../lib/resources.py", line 176, in action
    r.action(action)
  File "/service/etc/../lib/resources.py", line 84, in action
    self.do_action(action)
  File "/service/etc/../lib/resources.py", line 65, in do_action
    return getattr(self, action)()
  File "/service/etc/../lib/resDg.py", line 59, in scsireserv
    if not allow_scsireserv(self):
  File "/service/etc/../lib/resDg.py", line 32, in allow_scsireserv
    if not scsiReserv.scsireserv_supported():
  File "/service/etc/../lib/scsiReserv.py", line 30, in scsireserv_supported
    if which('sg_persist') is None:
NameError: global name 'which' is not defined