Beautify the disk.scsireserv resource log when paths are down
Example:

  `- disk#10pr      ....... undef      /dev/sdl, /dev/sdn, /dev/sdo, /dev/sdp
                                       warn: disk /dev/sdn does not support persistent reservation
                                       warn: disk /dev/sdp does not support persistent reservation
                                       error: device /dev/mapper/ does not exist

The err log is not useful there.