Fix a string wildcard substitution pattern in the listener codepath
Causing:

Server Traceback (most recent call last):
  File "/opt/opensvc/lib/osvcd_lsnr.py", line 876, in h2_router
    result = self.router(None, data, stream_id=stream_id)
  File "/opt/opensvc/lib/osvcd_lsnr.py", line 1532, in router
    return getattr(self, fname)(nodename, action=action, options=options, stream_id=stream_id)
  File "/opt/opensvc/lib/osvcd_lsnr.py", line 1917, in action_wake_monitor
    shared.wake_monitor(reason="node notification" % path)
TypeError: not all arguments converted during string formatting