Fix another stack in Freenas array driver
[root@infra-1 freenas]# nodemgr array --array freenas del iscsi target --id 1
Traceback (most recent call last):
  File "/usr/share/opensvc/lib/nodemgr.py", line 110, in <module>
    ret = main()
  File "/usr/share/opensvc/lib/nodemgr.py", line 102, in main
    return _main(node, argv=argv)
  File "/usr/share/opensvc/lib/nodemgr.py", line 82, in _main
    err = node.action(action)
  File "/usr/share/opensvc/lib/node.py", line 1005, in action
    return self._action(action, options)
  File "/usr/share/opensvc/lib/rcScheduler.py", line 113, in _func
    ret = func(self, action, options)
  File "/usr/share/opensvc/lib/node.py", line 1036, in _action
    ret = getattr(self, action)()
  File "/usr/share/opensvc/lib/node.py", line 2129, in array
    return mod.main(self.options.extra_argv, node=self)
  File "/usr/share/opensvc/lib/rcFreenas.py", line 863, in main
    do_action(action, node=node, **kwargs)
  File "/usr/share/opensvc/lib/rcFreenas.py", line 853, in do_action
    result = getattr(array, action)(**kwargs)
  File "/usr/share/opensvc/lib/rcFreenas.py", line 654, in del_iscsi_target
    content = self.get_iscsi_target_id(target_id)
  File "/usr/share/opensvc/lib/rcFreenas.py", line 344, in get_iscsi_target_id
    buff = self.get("/services/iscsi/target/%d" % tgt_id)
TypeError: %d format: a number is required, not NoneType