Verify that the ipdev is present in allow_start() before using its ifconfig information.
This bug caused this stack :

[root@s64lmwbic3v ~]# /service/etc/iisprdora01 start
Traceback (most recent call last):
  File "/service/etc/../lib/svc.py", line 193, in action
    getattr(self, action)()
  File "/service/etc/../lib/svcHosted.py", line 41, in start
    self.sub_set_action("ip", "start")
  File "/service/etc/../lib/svc.py", line 87, in sub_set_action
    r.action(action)
  File "/service/etc/../lib/resources.py", line 179, in action
    r.action(action)
  File "/service/etc/../lib/resources.py", line 85, in action
    self.do_action(action)
  File "/service/etc/../lib/resources.py", line 65, in do_action
    getattr(self, action)()
  File "/service/etc/../lib/resIp.py", line 102, in start
    self.allow_start()
  File "/service/etc/../lib/resIp.py", line 89, in allow_start
    if not ifconfig.interface(self.ipDev).flag_up:
AttributeError: 'NoneType' object has no attribute 'flag_up'