Fix python 2.4 stack in postinstall
"any" python builtin was introduced in python 2.5

Traceback (most recent call last):
  File "/opt/opensvc/bin/postinstall", line 1396, in ?
    install_rc()
  File "/opt/opensvc/bin/postinstall", line 806, in install_rc
    if not is_system_locale_utf8() and not is_osvc_locale_utf8(params):
  File "/opt/opensvc/bin/postinstall", line 573, in is_system_locale_utf8
    return is_lang_utf8(localetmp)
  File "/opt/opensvc/bin/postinstall", line 559, in is_lang_utf8
    if any(pattern in lang for pattern in utf8patterns):
NameError: global name 'any' is not defined