Fix a potential stack in the monitor thread
Now that the daemon accepts to relay a global_expect for a foreign node, the
following stack has become possible:

Traceback (most recent call last):
  File "/opt/opensvc/lib/osvcd_mon.py", line 119, in run
    self.do()
  File "/opt/opensvc/lib/osvcd_mon.py", line 180, in do
    self.orchestrator()
  File "/opt/opensvc/lib/osvcd_mon.py", line 650, in orchestrator
    self.service_orchestrator(svcname, svc)
  File "/opt/opensvc/lib/osvcd_mon.py", line 823, in service_orchestrator
    self.set_smon_g_expect_from_status(svcname, smon, status)
  File "/opt/opensvc/lib/osvcd_mon.py", line 2603, in set_smon_g_expect_from_status
    candidates = self.placement_candidates(svc, discard_start_failed=False, discard_frozen=False)
  File "/opt/opensvc/lib/osvcd_shared.py", line 817, in placement_candidates
    if nodename not in svc.peers:
AttributeError: 'NoneType' object has no attribute 'peers'

Meaning the placement_candidates() was called with svc=None.

Just return an empty list in this case.