Handle self.mountpoint going to None during disk.volume data_data() execution
Caused:

Traceback (most recent call last):
  File "/opt/opensvc/lib/osvcd_mon.py", line 328, in fetch_service_config
    svc.postinstall()
  File "/opt/opensvc/lib/data.py", line 163, in postinstall
    if vol.has_data(self.kind, self.svcpath, key) and vol._status() == rcStatus.UP:
  File "/opt/opensvc/lib/resVolume.py", line 133, in has_data
    for data in self.data_data(kind):
  File "/opt/opensvc/lib/resVolume.py", line 115, in data_data
    path = self.mount_point.rstrip(os.sep) + os.sep
AttributeError: 'NoneType' object has no attribute 'rstrip'