Don't stack when dbopensvc is set but dbcompliance is not
If etc/node.conf has a valid dbopensvc url set, but dbcompliance
is not set, the agent would stack with:

Traceback (most recent call last):
  File "/opt/opensvc/bin/nodemgr", line 157, in <module>
    err = n.action(action)
  File "/opt/opensvc/lib/node.py", line 464, in action
    return getattr(self, a)()
  File "/opt/opensvc/lib/node.py", line 553, in pushasset
    self.task_pushasset()
  File "/opt/opensvc/lib/rcScheduler.py", line 82, in _fn
    fn(*args, **kwargs)
  File "/opt/opensvc/lib/node.py", line 557, in task_pushasset
    self.collector.call('push_asset', self)
  File "/opt/opensvc/lib/xmlrpcClient.py", line 199, in call
    self.init(fn)
  File "/opt/opensvc/lib/xmlrpcClient.py", line 312, in init
    self.log.error("could not resolve %s to an ip address. disable collector updates."%rcEnv.dbcompliance_host)
AttributeError: class rcEnv has no attribute 'dbcompliance_host'

This patch, traps this case and makes sure the dbopensvc feed
api is usable, even if the compliance api is not.