[test] Disable create_pg during tests
Without this fix, following test wills fail:
   pytest -m ci -k 'test_run_task or test_service_hooks'

   => test_run_task create freezer for service named pytest: /sys/fs/cgroup/freezer/opensvc.slice/pytest.slice
   => test_service_hooks use service named pytest => during shutdown action, self.pg_remove is called

Output example
___________________________________________________________ TestSvcHooks.test_call_shutdown_action_stop_hook[pre] ___________________________________________________________

mocker = <pytest_mock.plugin.MockerFixture object at 0x7f6ffc5be2e8>, osvc_path_tests = local('/tmp/pytest-of-root/pytest-40/test_call_shutdown_action_stop0')
prefix = 'pre'

    @staticmethod
    @pytest.mark.parametrize(
        'prefix',
        ['pre', 'post', 'blocking_pre', 'blocking_post']
    )
    def test_call_shutdown_action_stop_hook(mocker, osvc_path_tests, prefix):
        svcname = "pytest"
        mocker.patch.dict(os.environ, {'OSVC_DETACHED': '1'})
        hook = '%s_stop' % prefix
        assert_run_cmd_success(svcname, ['create', '--kw', 'DEFAULT.%s=/usr/bin/touch {private_var}/%s' % (hook, hook)])
>       assert_run_cmd_success(svcname, ['shutdown', '--local', '--debug'])

/opt/opensvc/opensvc/tests/commands/svc/test_service_hooks.py:59:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

svcname = 'pytest', svc_cmd_args = ['shutdown', '--local', '--debug']

    def assert_run_cmd_success(svcname, svc_cmd_args):
        cmd_args = ["-s", svcname] + svc_cmd_args
        print('--------------')
        print('run Mgr()(argv=%s)' % cmd_args)
>       assert Mgr()(argv=cmd_args) == 0
E       AssertionError: assert 1 == 0
E        +  where 1 = <commands.svc.Mgr object at 0x7f6ffc6075c0>(argv=['-s', 'pytest', 'shutdown', '--local', '--debug'])
E        +    where <commands.svc.Mgr object at 0x7f6ffc6075c0> = Mgr()

/opt/opensvc/opensvc/tests/commands/svc/test_service_hooks.py:12: AssertionError
--------------------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------------------
--------------
run Mgr()(argv=['-s', 'pytest', 'create', '--kw', 'DEFAULT.pre_stop=/usr/bin/touch {private_var}/pre_stop'])
create pytest
--------------
run Mgr()(argv=['-s', 'pytest', 'shutdown', '--local', '--debug'])
--------------------------------------------------------------------------- Captured stderr call ----------------------------------------------------------------------------
W [Errno 2] No such file or directory
  pre_stop: /usr/bin/touch /tmp/pytest-of-root/pytest-40/test_call_shutdown_action_stop0/var/svc/pytest/pre_stop
  kill 1208455
E interrupted by signal
W post object status failed: [Errno 2] No such file or directory
E [Errno 2] No such file or directory
========================================================================== short test summary info ==========================================================================
FAILED ../opt/opensvc/opensvc/tests/commands/svc/test_service_hooks.py::TestSvcHooks::test_call_shutdown_action_stop_hook[pre] - AssertionError: assert 1 == 0
=================================================== 1 failed, 2718 passed, 37 skipped, 114 deselected in 79.29s (0:01:19) ==================================================