Fix the daemon start codepath when a fs.docker resource is defined
fs.docker does not have a mount_pount property. Don't assume all fs
resources have one.

The symptom was:

Traceback (most recent call last):
  File "/usr/share/opensvc/lib/svc.py", line 3975, in do_action
    err = call_action(action)
  File "/usr/share/opensvc/lib/svc.py", line 3964, in call_action
    err = getattr(self, action)()
  File "/usr/share/opensvc/lib/svc.py", line 4645, in docker
    self.dockerlib.docker_start(verbose=False)
  File "/usr/share/opensvc/lib/rcDocker.py", line 722, in docker_start
    resource = self._docker_data_dir_resource()
  File "/usr/share/opensvc/lib/rcDocker.py", line 690, in _docker_data_dir_resource
    mntpts.append(resource.mount_point)
AttributeError: 'Fs' object has no attribute 'mount_point'