Fix last commit missing '--disable_rollback' during orchestrate service_provision
o regression in #e34b795c4a8dcaacf5e559f9f5374480386516c0
  with stack
  Traceback (most recent call last):
    File "opensvc/daemon/monitor.py", line 712, in run
      self.do()
    File "opensvc/daemon/monitor.py", line 790, in do
      self.orchestrator()
    File "opensvc/daemon/monitor.py", line 1485, in orchestrator
      self.object_orchestrator(path, svc)
    File "opensvc/daemon/monitor.py", line 1720, in object_orchestrator
      self.object_orchestrator_manual(svc, smon, agg.avail)
    File "opensvc/daemon/monitor.py", line 125, in object_orchestrator_manual
      fn(**kwargs)
    File "opensvc/daemon/monitor.py", line 365, in _oom_provisioned
      step_provision()
    File "opensvc/daemon/monitor.py", line 359, in step_provision
      self.service_provision(svc)
    File "opensvc/daemon/monitor.py", line 1208, in service_provision
      cmd += ["--leader", "--disable-rollback"]
  UnboundLocalError: local variable 'cmd' referenced before assignment