Fix wrong exception name in fs stop error code path
Fixes:

File "/opt/opensvc/lib/resources.py", line 569, in action
    r.action(action)
  File "/opt/opensvc/lib/resources.py", line 219, in action
    self.do_action(action)
  File "/opt/opensvc/lib/resources.py", line 173, in do_action
    self.action_main(action)
  File "/opt/opensvc/lib/resources.py", line 158, in action_main
    getattr(self, action)()
  File "/opt/opensvc/lib/resMountLinux.py", line 358, in stop
    raise execError('mount point %s does not exist' % self.mountPoint)
NameError: global name 'execError' is not defined