[lock] Create lockdir may fail
This patch prevent errors when multiples locks are created on not yet created lock dir

    INFO sid:3c19d8d5-3672-495c-ac5b-46ec6f4caf31 n:node-1 o:0.svc1 sc:n | do start --local (daemon origin)
    ERROR sid:3c19d8d5-3672-495c-ac5b-46ec6f4caf31 n:node-1 o:0.svc1 r:volume#0 sc:n | volume volume-secrets does not exist
    INFO sid:3c19d8d5-3672-495c-ac5b-46ec6f4caf31 n:node-1 o:0.svc1 sc:n | skip rollback start: no resource activated
    INFO sid:6622111d-1780-48eb-aa96-0d55cbb39255 n:node-1 o:0.svc1 sc:n | do provision --local --disable-rollback --leader (daemon origin)
    ERROR sid:6622111d-1780-48eb-aa96-0d55cbb39255 n:node-1 o:0.svc1 sc:n | a stack has been saved in the logs
    Traceback (most recent call last):
      File "/usr/share/opensvc/opensvc/utilities/lock/__init__.py", line 155, in lock_nowait
        lockfd = os.open(lockfile, flags, 0o644)
    FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/opensvc/vol/volume-secrets/create_volume.lock'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/share/opensvc/opensvc/core/objects/svc.py", line 1142, in do_action
        err = call_action(action)
      File "/usr/share/opensvc/opensvc/core/objects/svc.py", line 1131, in call_action
        err = getattr(self, action)()
      File "/usr/share/opensvc/opensvc/core/objects/svc.py", line 4540, in provision
        self.master_provision()
      File "/usr/share/opensvc/opensvc/core/objects/svc.py", line 492, in _func
        func(self)
      File "/usr/share/opensvc/opensvc/core/objects/svc.py", line 4545, in master_provision
        self.sub_set_action(START_GROUPS, "provision", xtags=set(["zone", "docker", "podman"]))
      File "/usr/share/opensvc/opensvc/core/objects/svc.py", line 3576, in sub_set_action
        self.set_action(rsets, _type=_type, action=action, tags=tags, xtags=xtags)
      File "/usr/share/opensvc/opensvc/core/objects/svc.py", line 3666, in set_action
        rset.action(action, types=_type, tags=tags, xtags=xtags, xtypes=aborted)
      File "/usr/share/opensvc/opensvc/core/resourceset.py", line 346, in action
        resource.action(action)
      File "/usr/share/opensvc/opensvc/core/resource.py", line 465, in action
        self.do_action(action)
      File "/usr/share/opensvc/opensvc/core/resource.py", line 369, in do_action
        self.action_main(action)
      File "/usr/share/opensvc/opensvc/core/resource.py", line 338, in action_main
        getattr(self, action)()
      File "/usr/share/opensvc/opensvc/core/resource.py", line 1244, in provision
        self._provision()
      File "/usr/share/opensvc/opensvc/core/resource.py", line 1268, in _provision
        getattr(self, "provisioner")()
      File "/usr/share/opensvc/opensvc/drivers/resource/volume/__init__.py", line 637, in provisioner
        volume = self.create_volume()
      File "/usr/share/opensvc/opensvc/drivers/resource/volume/__init__.py", line 672, in create_volume
        with utilities.lock.cmlock(lockfile=lockfile, timeout=20):
      File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/share/opensvc/opensvc/utilities/lock/__init__.py", line 93, in cmlock
        lockfd = lock(*args, **kwargs)
      File "/usr/share/opensvc/opensvc/utilities/lock/__init__.py", line 112, in lock
        return lock_nowait(lockfile, intent)
      File "/usr/share/opensvc/opensvc/utilities/lock/__init__.py", line 158, in lock_nowait
        os.makedirs(lock_dir)
      File "/usr/lib64/python3.6/os.py", line 220, in makedirs
        mkdir(name, mode)
    FileExistsError: [Errno 17] File exists: '/var/lib/opensvc/vol/volume-secrets'