Fix the sym array actions
Using a non existent Node::logger attribute.
Causing:

Traceback (most recent call last):
  File "/usr/share/opensvc/lib/nodemgr.py", line 113, in <module>
    ret = main()
  File "/usr/share/opensvc/lib/nodemgr.py", line 102, in main
    return _main(node, argv=argv)
  File "/usr/share/opensvc/lib/nodemgr.py", line 82, in _main
    err = node.action(action)
  File "/usr/share/opensvc/lib/node.py", line 1076, in action
    return self._action(action, options)
  File "/usr/share/opensvc/lib/rcScheduler.py", line 114, in _func
    ret = func(self, action, options)
  File "/usr/share/opensvc/lib/node.py", line 1106, in _action
    ret = getattr(self, action)()
  File "/usr/share/opensvc/lib/node.py", line 2256, in array
    return mod.main(self.options.extra_argv, node=self)
  File "/usr/share/opensvc/lib/rcSymmetrix.py", line 1455, in main
    do_action(action, node=node, **kwargs)
  File "/usr/share/opensvc/lib/rcSymmetrix.py", line 1442, in do_action
    node.logger.handlers[1].setLevel(logging.CRITICAL)
AttributeError: 'Node' object has no attribute 'logger'