nodemgr actions fix
Fix this stack, introduced by the --user register option:

Traceback (most recent call last):
  File "/opt/opensvc/bin/svcmgr", line 337, in <module>
    r = pull_service(svcnames)
  File "/opt/opensvc/bin/svcmgr", line 58, in pull_service
    node.pull(svcname)
  File "/opt/opensvc/lib/node.py", line 1567, in pull
    data = self.collector_rest_get("/services/"+svcname+"?props=svc_envfile&meta=0")
  File "/opt/opensvc/lib/node.py", line 1498, in collector_rest_get
    return self.collector_rest_request(path)
  File "/opt/opensvc/lib/node.py", line 1504, in collector_rest_request
    api = self.collector_api()
  File "/opt/opensvc/lib/node.py", line 1445, in collector_api
    if self.options.user is None:
AttributeError: 'Options' object has no attribute 'user'