Add a check=last_run keyword to task drivers
Now task resources remember the return code of their last run.

With check=last_run, this last return code is used to set a resource status,
if run_requires is not set, or set and validated.

Example:

[task#2]
command = /bin/false
run_requires = container#1(up)
schedule = @1
check = last_run

$ om svc2 print status
svc2                             up         warn
`- instances
   `- aubergine                  up         warn, frozen, idle, started
      |- ip#0           ........ up         cni default 10.22.0.200/16 eth12
      |- container#0    ........ up         podman docker.io/google/pause
      |- container#1    ........ up         podman docker.io/library/busybox
      |- container#2    ...../.. up         podman docker.io/library/busybox
      |- task#1         ...O.... down       podman docker.io/library/busybox
      |                                     error: last run failed
      `- task#2         ...O.... down       task.host
                                            error: last run failed

Stop the task#2-required resource:

$ om svc2 stop --rid container#1

$ om svc2 print status
svc2                             warn       warn
`- instances
   `- aubergine                  warn       warn, frozen, stopping, started
      ...
      |- container#1    ........ down       podman docker.io/library/busybox
      ...
      `- task#2         ...O.... n/a        task.host