Filter out None values in the None value in the resources_by_id hash
Causing the following stack after resource expansion:

Traceback (most recent call last):
File "/opt/opensvc/etc/spdsvc01", line 406, in <module>
err = node.do_svcs_action(action, rid=rid, tags=tags, subsets=subsets)
File "/opt/opensvc/lib/node.py", line 1417, in do_svcs_action
err += s.action(action, rid=rid, tags=tags, subsets=subsets, waitlock=self.options.waitlock)
File "/opt/opensvc/lib/svc.py", line 2422, in action
self.log.debug("rids retained after expansions intersection: %s" % ";".join(rids))
TypeError: sequence item 28: expected string, NoneType found