Fix an UnboundLocalError introduced by the previous commit
Traceback (most recent call last):
  File "/usr/share/opensvc/opensvc/core/objects/svc.py", line 1131, in do_action
    err = call_action(action)
  File "/usr/share/opensvc/opensvc/core/objects/svc.py", line 1120, in call_action
    err = getattr(self, action)()
  File "/usr/share/opensvc/opensvc/core/objects/svc.py", line 4520, in provision
    self.master_provision()
  File "/usr/share/opensvc/opensvc/core/objects/svc.py", line 485, in _func
    func(self)
  File "/usr/share/opensvc/opensvc/core/objects/svc.py", line 4530, in master_provision
    self.rollback()
  File "/usr/share/opensvc/opensvc/core/objects/svc.py", line 4459, in rollback
    self.sub_set_action(STOP_GROUPS, "rollback", xtags=set(["zone", "docker", "podman"]))
  File "/usr/share/opensvc/opensvc/core/objects/svc.py", line 3557, in sub_set_action
    self.set_action(rsets, _type=_type, action=action, tags=tags, xtags=xtags)
  File "/usr/share/opensvc/opensvc/core/objects/svc.py", line 3647, in set_action
    rset.action(action, types=_type, tags=tags, xtags=xtags, xtypes=aborted)
  File "/usr/share/opensvc/opensvc/core/resourceset.py", line 330, in action
    resource.action(action)
  File "/usr/share/opensvc/opensvc/core/resource.py", line 462, in action
    self.do_action(action)
  File "/usr/share/opensvc/opensvc/core/resource.py", line 366, in do_action
    self.action_main(action)
  File "/usr/share/opensvc/opensvc/core/resource.py", line 335, in action_main
    getattr(self, action)()
  File "/usr/share/opensvc/opensvc/core/resource.py", line 884, in rollback
    self.stop()
  File "/usr/share/opensvc/opensvc/drivers/resource/container/docker/__init__.py", line 931, in stop
    self._stop()
  File "/usr/share/opensvc/opensvc/drivers/resource/container/podman/__init__.py", line 113, in _stop
    BaseContainer.stop(self)
  File "/usr/share/opensvc/opensvc/drivers/resource/container/__init__.py", line 331, in stop
    if self.is_down():
  File "/usr/share/opensvc/opensvc/drivers/resource/container/docker/__init__.py", line 1058, in is_down
    return not self.is_up()
  File "/usr/share/opensvc/opensvc/drivers/resource/container/podman/__init__.py", line 134, in is_up
    if self.container_id in self.lib.get_running_instance_ids():
  File "/usr/share/opensvc/opensvc/utilities/subsystems/docker.py", line 215, in get_running_instance_ids
    return self.running_instance_ids
  File "/usr/share/opensvc/opensvc/utilities/lazy.py", line 10, in _lazyprop
    setattr(self, attr_name, fn(self))
  File "/usr/share/opensvc/opensvc/utilities/subsystems/docker.py", line 234, in running_instance_ids
    if cid:
UnboundLocalError: local variable 'cid' referenced before assignment