[utilities] Fix pushasset python2.7 error on datetime.timestamp()
Introduce `as_timestamp` utility for python2.7 compat
and update Linux asset for timestamp conversion

This commit fixes python2.7 traceback during pushasset:
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/usr/share/opensvc/opensvc/__main__.py", line 131, in <module>
        ret = main(sys.argv)
      File "/usr/share/opensvc/opensvc/__main__.py", line 103, in main
        ret = main(argv=argv[2:])
      File "/usr/share/opensvc/opensvc/commands/node/__init__.py", line 65, in main
        return _main(node, argv=argv)
      File "/usr/share/opensvc/opensvc/commands/node/__init__.py", line 45, in _main
        err = node.action(action)
      File "/usr/share/opensvc/opensvc/core/node/node.py", line 1029, in action
        return self._action(action, options)
      File "/usr/share/opensvc/opensvc/core/scheduler.py", line 177, in _func
        ret = func(self, action, options)
      File "/usr/share/opensvc/opensvc/core/node/node.py", line 1059, in _action
        ret = getattr(self, action)()
      File "/usr/share/opensvc/opensvc/core/node/node.py", line 1204, in pushasset
        system_dict = self.asset.get_system_dict()
      File "/usr/share/opensvc/opensvc/utilities/asset/asset.py", line 749, in get_system_dict
        data["properties"] = self.get_asset_properties()
      File "/usr/share/opensvc/opensvc/utilities/asset/asset.py", line 681, in get_asset_properties
        last_boot = self.get_last_boot()
      File "/usr/share/opensvc/opensvc/utilities/asset/linux.py", line 760, in get_last_boot
        "value": last.timestamp(),
    AttributeError: 'datetime.datetime' object has no attribute 'timestamp'