[test] Fix mock error during test_orchestrator_start.py
Because NMON_DATA value is created during module import,
mocker.patch.dict(shared.NMON_DATA, {}) may raise AttributeError

detail here:

    def _start_patch(
        self, mock_func: Any, warn_on_mock_enter: bool, *args: Any, **kwargs: Any
    ) -> unittest.mock.MagicMock:
        """Patches something by calling the given function from the mock
        module, registering the patch to stop it later and returns the
        mock object resulting from the mock call.
        """
        p = mock_func(*args, **kwargs)
        mocked = p.start()  # type: unittest.mock.MagicMock
        self._patches.append(p)
        if hasattr(mocked, "reset_mock"):
            self._mocks.append(mocked)
            # check if `mocked` is actually a mock object, as depending on autospec or target
            # parameters `mocked` can be anything
            if hasattr(mocked, "__enter__") and warn_on_mock_enter:
                if sys.version_info >= (3, 8):
                    depth = 5
                else:
                    depth = 4
>               mocked.__enter__.side_effect = lambda: warnings.warn(
                    "Mocks returned by pytest-mock do not need to be used as context managers. "
                    "The mocker fixture automatically undoes mocking at the end of a test. "
                    "This warning can be ignored if it was triggered by mocking a context manager. "
                    "https://github.com/pytest-dev/pytest-mock#note-about-usage-as-context-manager",
                    PytestMockWarning,
                    stacklevel=depth,
                )
E               AttributeError: 'NoneType' object has no attribute 'side_effect'