Improve detection of osvcd process
This should allow again tests in gitlab ci or travis for nodemgr_daemon

It requires:
 o procps for ps -p ... -o args=
 o need sudo for is_container()
   PermissionError: [Errno 13] Permission denied: '/proc/1/environ'