Fix stack due to Svc::config changes
Traceback (most recent call last):
  File "/opt/opensvc/lib/svc.py", line 1035, in do_action
    err = call_action(action)
  File "/opt/opensvc/lib/svc.py", line 1024, in call_action
    err = getattr(self, action)()
  File "/opt/opensvc/lib/svc.py", line 4215, in start
    self.master_start()
  File "/opt/opensvc/lib/svc.py", line 434, in _func
    func(self)
  File "/opt/opensvc/lib/svc.py", line 4220, in master_start
    self.sub_set_action(START_GROUPS, "start", xtags=set(["zone", "docker", "podman"]))
  File "/opt/opensvc/lib/svc.py", line 3271, in sub_set_action
    self.set_action(rsets, _type=_type, action=action, tags=tags, xtags=xtags)
  File "/opt/opensvc/lib/svc.py", line 3361, in set_action
    rset.action(action, types=_type, tags=tags, xtags=xtags, xtypes=aborted)
  File "/opt/opensvc/lib/resourceset.py", line 326, in action
    resource.action(action)
  File "/opt/opensvc/lib/resources.py", line 413, in action
    self.do_action(action)
  File "/opt/opensvc/lib/resources.py", line 317, in do_action
    self.action_main(action)
  File "/opt/opensvc/lib/resources.py", line 286, in action_main
    getattr(self, action)()
  File "/opt/opensvc/lib/resIp.py", line 412, in start
    self.dns_update()
  File "/opt/opensvc/lib/resIp.py", line 468, in dns_update
    if self.node.collector_env.dbopensvc is None:
AttributeError: 'Ip' object has no attribute 'node'