Fix a stack in logging when multiple [syslog] sections are defined
--- Logging error ---
Traceback (most recent call last):
  File "/opt/python3/lib/python3.7/logging/handlers.py", line 927, in emit
    self.mapPriority(record.levelname))
  File "/opt/python3/lib/python3.7/logging/handlers.py", line 884, in encodePriority
    return (facility << 3) | priority
TypeError: unsupported operand type(s) for <<: 'list' and 'int'