Fix the 'json_status' action
The stack was

Traceback (most recent call last):
  File "/opt/opensvc/lib/svc.py", line 1075, in do_action
    getattr(self, action)()
  File "/opt/opensvc/lib/svc.py", line 373, in json_status
    rid, status, label, log, monitor = r.status_quad()
ValueError: too many values to unpack

It was due to quad_status() returning the additional 'disabled'
and 'optional' items in the returned list.