Remove python 2.6.2 on sol 8 & 9 multiprocessing bug workaround
Now that we prepend lib/ to the sys.path, this workaround breaks
things with the Queue users.

The visible symptom is this stack in the syncnodes codepath:

Traceback (most recent call last):
  File "/opt/opensvc/lib/svc.py", line 2525, in do_action
    err = getattr(self, action)()
  File "/opt/opensvc/lib/svc.py", line 2021, in sync_nodes
    self.remote_postsync()
  File "/opt/opensvc/lib/svc.py", line 1975, in remote_postsync
    self.remote_action(n, 'postsync', waitlock=3600)
  File "/opt/opensvc/lib/svc.py", line 1999, in remote_action
    self.node.cmdworker.enqueue(cmd)
  File "/opt/opensvc/lib/rcCommandWorker.py", line 76, in enqueue
    self.start_worker()
  File "/opt/opensvc/lib/rcCommandWorker.py", line 66, in start_worker
    self.q = Queue()
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 217, in Queue
    from multiprocessing.queues import Queue
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 48, in <module>
    from multiprocessing.synchronize import Lock, BoundedSemaphore, Semaphore, Condition
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 59, in <module>
    " function, see issue 3770.")
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.