Catch TypeError when getting CLUSTER_DATA[nodename]["services"]["status"][svcname]
In addition to catching KeyError, because one of the data in the chain might be None.

For example, the following stack has been observed:

Traceback (most recent call last):
  File "/opt/opensvc/lib/osvcd_mon.py", line 119, in run
    self.do()
  File "/opt/opensvc/lib/osvcd_mon.py", line 178, in do
    self.update_cluster_data()
  File "/opt/opensvc/lib/osvcd_mon.py", line 2675, in update_cluster_data
    data["services"]["status"] = self.get_services_status(data["services"]["config"].keys())
  File "/opt/opensvc/lib/osvcd_mon.py", line 2428, in get_services_status
    last_mtime = self.get_last_svc_status_mtime(svcname)
  File "/opt/opensvc/lib/osvcd_mon.py", line 2383, in get_last_svc_status_mtime
    instance = self.get_service_instance(svcname, rcEnv.nodename)
  File "/opt/opensvc/lib/osvcd_shared.py", line 754, in get_service_instance
    CLUSTER_DATA[nodename]["services"]["status"][svcname]
TypeError: 'NoneType' object is not iterable