Set 'UTF-8' as a fallback encoding when sys.stdin.encoding is None
This fixes the following stack when "nodemgr set" is used from
debian postinst script.

Traceback (most recent call last):
  File "/usr/share/opensvc/lib/nodemgr.py", line 101, in <module>
    ret = main()
  File "/usr/share/opensvc/lib/nodemgr.py", line 93, in main
    return _main(node, argv=argv)
  File "/usr/share/opensvc/lib/nodemgr.py", line 73, in _main
    err = node.action(action)
  File "/usr/share/opensvc/lib/node.py", line 719, in action
    ret = getattr(self, action)()
  File "/usr/share/opensvc/lib/node.py", line 1561, in set
    self.write_config()
  File "/usr/share/opensvc/lib/node.py", line 575, in write_config
    self.config.write(tmpf)
  File "/usr/share/opensvc/lib/rcConfigParser.py", line 31, in write
    value = value.decode(sys.stdin.encoding)
TypeError: decode() argument 1 must be string, not None

Reported by Jean-Michel Kelbert.