Fix a stack in the xmlrpc code
The stack is:

Process xmlrpc:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/opensvc/lib/xmlrpcClient.py", line 107, in call_worker
    o.init()
  File "/opt/opensvc/lib/xmlrpcClient.py", line 268, in init
    self.setNodeEnv()
  File "/opt/opensvc/lib/xmlrpcClient.py", line 148, in setNodeEnv
    if self.node.config.has_option('node', 'dbopensvc'):
AttributeError: 'NoneType' object has no attribute 'config'

It's a regression from the node.conf access through the node object in the
xmlrpc code.