Add a sanity check on the result of the service status eval before use
To avoid this stack observed in logs:

Traceback (most recent call last):
  File "/usr/share/opensvc/lib/osvcd_mon.py", line 113, in run
    self.do()
  File "/usr/share/opensvc/lib/osvcd_mon.py", line 176, in do
    self.update_hb_data()
  File "/usr/share/opensvc/lib/osvcd_mon.py", line 2657, in update_hb_data
    self.update_cluster_data()
  File "/usr/share/opensvc/lib/osvcd_mon.py", line 2637, in update_cluster_data
    data["services"]["status"] = self.get_services_status(data["services"]["config"].keys())
  File "/usr/share/opensvc/lib/osvcd_mon.py", line 2424, in get_services_status
    data[svcname]["frozen"] = shared.SERVICES[svcname].frozen()
TypeError: 'NoneType' object does not support item assignment