Add missing disable_rollback property to svc object options
Which fixes this stack :

Traceback (most recent call last):
  File "/opt/opensvc/etc/win2.opensvc.com", line 218, in <module>
    node.build_services(svcnames=svcname)
  File "/opt/opensvc/lib/node.py", line 248, in build_services
    svc.action('push')
  File "/opt/opensvc/lib/svc.py", line 1976, in action
    err = self.do_action(action, waitlock=waitlock)
  File "/opt/opensvc/lib/svc.py", line 2034, in do_action
    self.rollback_handler(action)
  File "/opt/opensvc/lib/svc.py", line 2049, in rollback_handler
    if self.options.disable_rollback:
AttributeError: 'Options' object has no attribute 'disable_rollback'