Fix stack in resource restart block
Due to wrong module name.

This fixes the following stack:

Traceback (most recent call last):
  File "/opt/opensvc/lib/svc.py", line 2721, in do_action
    err = getattr(self, action)()
  File "/opt/opensvc/lib/svc.py", line 596, in json_status
    rid, rtype, status, label, log, monitor, disable, optional, encap = r.status_quad()
  File "/opt/opensvc/lib/resources.py", line 417, in status_quad
    r = self.status(verbose=True)
  File "/opt/opensvc/lib/resources.py", line 279, in status
    self.do_restart(last_status)
  File "/opt/opensvc/lib/resources.py", line 320, in do_restart
    except ex.excError:
NameError: global name 'ex' is not defined