Fix pylint errors in the disk.gandi driver
************* Module resDiskGandi
lib/resDiskGandi.py:193:30: E1305: Too many arguments for format string (too-many-format-args)

=> add the missing %s, placeholder for the exc string

lib/resDiskGandi.py:47:19: E0203: Access to member 'cloud' before its definition line 49 (access-member-before-definition)

=> use a lazy attr for self.cloud instead of the free-style cache